[build]
  # Directory to change to before starting a build
  base = "/"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  
  # Default build command
  command = "npm run build"

[build.environment]
  # Node version for build
  NODE_VERSION = "18"
  
  # Prevent Netlify from processing forms
  NETLIFY_SKIP_FORMS_PROCESSING = "true"

# Redirect rules for SPA (Single Page Application) routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://everwell-1127.azurewebsites.net https://localhost:7050;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API proxy rules (if needed for CORS)
[[redirects]]
  from = "/api/*"
  to = "https://everwell-1127.azurewebsites.net/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}